parameters:
    comgate:
        merchant: '%env(MERCHANT_ID)%'
        secret: '%env(SECRET_KEY)%'
        test: '%env(TEST_MODE)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mysho\ComgateBundle\Service\ComgateConnector:
        arguments:
            $params: '%comgate%'

    Mysho\ComgateBundle\Exception\:
        resource: '../../Exception/*'

    Mysho\ComgateBundle\Factory\:
        resource: '../../Factory/*'

    Mysho\ComgateBundle\Helper\:
        resource: '../../Helper/*'